### PR TITLE
add Info Box Hero Block

### PR DESCRIPTION
**Pull request by jyoung295**

### CODE REVIEW

**Review by Yanhuazong — COMMENTED** [review]
IS the background image supposed to be repetitive instead of cover?

**Comment by Yanhuazong** [comment]
Can we hide the subtext when it's empty and make the margin bottom of the title 0? This might cause problem later.

**Comment by jyoung295** [comment]
Oh I'm assuming both the title and content are required. Where do you see that the background isn't set to cover?

**Review by Yanhuazong — APPROVED** [review]
Looks good. Please merge.

**Pull request merged**
