### PR TITLE
Feat/add tabs block

### PR DESCRIPTION
**Pull request by Yanhuazong**
Add tab block as well as css and JS for three header table HTML.
XD: https://xd.adobe.com/view/9fb5eb84-15a4-4820-94e6-47a3991e42a4-cae6/
On test site: https://dev-purdue-wp-test.pantheonsite.io/tabs/
Thanks!

### CODE REVIEW

**Comment by jyoung295** [comment]
When I test this block on the page, why do the dates in the gold bar change alignment when all of the accordions are closed?

**Comment by Yanhuazong** [comment]
> When I test this block on the page, why do the dates in the gold bar change alignment when all of the accordions are closed?

That's because the width of the cells are auto adjusted by the content inside. When the table rows are collapsed their display is set as none so they don't have any properties including width so it's not possible to set the header cells' width according to the width of the collapsed cells.

**Comment by jyoung295** [comment]
That makes sense, nothing we can really do about that! Okays so it looks good then!

**Review by jyoung295 — APPROVED** [review]

**Comment by Yanhuazong** [comment]
Thanks!

**Pull request merged**
