### PR TITLE
add optional subtext option

### PR DESCRIPTION
**Pull request by jyoung295**

### CODE REVIEW

**Comment by Yanhuazong** [comment]
We'll need to remove the button when the button text or the link url is empty.

**Comment by jyoung295** [comment]
The CTA hero is meant to have a cta button, isn't there another hero that does that?

**Comment by Yanhuazong** [comment]
> The CTA hero is meant to have a cta button, isn't there another hero that does that?

Justine mentioned this request. I think it's because they probably need a layout with just a title on the left.

**Review by Yanhuazong — APPROVED** [review]
Looks good!

**Pull request merged**
